// client/bundle/error/module/app.vue
<template>
    <div class="error-content">
        <div class="error-layer">
            <div class="error-panel">
                <img src="/client/asset/image/error.png" alt="" />
                <p>{{msg}}}</p>
            </div>
        </div>
    </div>
</template>
<script>
    export default {
        data(){
            return {
                msg:'123'
            }
        }
    }
</script>

// client/bundle/error/module/app.jsx
import React, { Component } from "react";

class Error extends Component {
    static propTypes = {
        initialState: React.PropTypes.object
    }
    render() {
        const { msg } = this.props.initialState
        return (
            <div className="error-content">
                <div className="error-layer">
                    <div className="error-panel">
                        <img src="/client/asset/image/error.png" alt="" />
                        <p>{msg}</p>
                    </div>
                </div>
            </div>
        );
    }
}

Error.defaultProps = {
    error: {
        msg: ""
    }
}

export default Error
