// client/bundle/user/module/app.jsx
import React, { Component } from 'react'
import { connected } from 'redux-container'
import * as actions from './action.es6'

export class User extends Component {
    static propTypes = {
        user: React.PropTypes.object
    }
    render() {
        const { user } = this.props
        if (!user) {
            return null
        }
        return (
            <div className="common-container">
                <div className="panel panel-default">
                <div className="panel-heading common-header"><button className="back-button" onClick={()=>window.history.back()}>&lt;</button>{user.id}</div>
                <div className="panel-body">
                    <div className="user-title">
                    <img src={user.avatar_url} alt="" />
                    <span>
                    <p>{user.login}</p>
                    <p>{user.created_at}</p>
                    </span>
                </div>
                </div>
                </div>
            </div>
        )
    }
}

export default connected(state => ({ ...state.userReducer }), actions)(User)

// client/bundle/user/module/app.vue
<script>
import { mapState, mapActions } from 'vuex'
import actions from './action.es6'

export default {
    computed:{
        ...mapState({
            user:state=>state.user.user
        })
    },
    methods:{
        ...mapActions(Object.keys(actions)),
        goback(){
            history.back()
        }
    }
}
</script>

<template>
<div class="common-container">
    <div class="panel panel-default">
    <div class="panel-heading common-header"><button class="back-button" @click="goback()">&lt;</button>{{user.id}}</div>
    <div class="panel-body">
        <div class="user-title">
        <img :src="user.avatar_url" alt="" />
        <span>
        <p>{{user.login}}</p>
        <p>{{user.created_at}}</p>
        </span>
    </div>
    </div>
    </div>
</div>
</template>
