// client/detail/module/app.vue
<template>
<div class="container">
    <div class="header header-with-btn"><button class="btn" @click="goBack"><i class="fa fa-arrow-left" /></button>{{event.name}}</div>
    <div class="content">
        <div class="detail">
            <img :src="event.avatar" alt="" />
            <p>Title: {{event.title}}</p>
            <p>Created at: {{event.created_at}}</p>
            <p>{{event.message}}</p>
        </div>
    </div>
</div>
</template>

<script>
    import { mapState, mapActions } from 'vuex'
    import * as actions from './action'
    export default {
        computed: {
            ...mapState({
                event: state => state.detail
            })
        },
        methods: {
            goBack(){
                window.history.back()
            },
            ...mapActions(Object.keys(actions))
        }
    }
</script>

// client/bundle/detail/module/app.jsx
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { connected } from 'redux-container'
import * as actions from './action'

export class Detail extends Component {
    static propTypes = {
        actions: PropTypes.object,
        detail: PropTypes.object
    }
    render() {
        const { detail } = this.props
        if (!detail) {
            return null
        }
        return (
            <div className="container">
                <div className="header header-with-btn"><button className="btn" onClick={()=>window.history.back()}><i className="fa fa-arrow-left" /></button>{detail.name}</div>
                <div className="content">
                    <div className="detail">
                        <img src={detail.avatar} alt="" />
                        <p>Title: {detail.title}</p>
                        <p>Created at: {detail.created_at}</p>
                        <p>{detail.message}</p>
                    </div>
                </div>
            </div>
        )
    }
}

export default connected(state => state, actions)(Detail)
