// client/bundle/error/app.vue
<template>
     <div class="container error">
         <p>{{msg}}</p>
         <button @click="goBack">Back</button>
     </div>
</template>
<script>
    export default {
        data() {
            return { msg: '' }
        },
        methods: {
            goBack() {
                window.history.back()
            }
        }
    }
</script>

// client/bundle/error/app.jsx
import React from 'react'
import PropTypes from 'prop-types'

const Error = ({ initialState }) => (
    <div className="container error">
        <p>{initialState.msg}</p>
        <button onClick={()=>window.history.back()}>Back</button>
    </div>
)

Error.propTypes = {
    initialState: PropTypes.object
}

export default Error
